
export const userConstants = {
  USER_REQUEST : 'USER_REQUEST',
  USER_SUCCESS : 'USER_SUCCESS',
  USER_FAILED : 'USER_FAILED',


  USER_SET_REQUEST : 'USER_SET_REQUEST',
  USER_SET_SUCCESS : 'USER_SET_SUCCESS',
  USER_SET_FAILED : 'USER_SET_FAILED',
}
